### ISSUE TITLE
BBC podcasts - need Content-Disposition to get usable filenames

### ISSUE THREAD

**Issue by sourcejedi** [chessgriffin/mashpodder#11]
The BBC changed them recently :(.  This approach has also been suggested as a solution to issue #10.  Unfortunately coding this is a bit hairy because of the existing fix_url() hacks.  Some fixing probably needs to be applied to both the download url, and the filename provided in Content-Disposition (e.g. assuming we're still against spaces in filenames).

http://www.bbc.co.uk/programmes/b015sqc7/episodes/downloads

Location: http://open.live.bbc.co.uk/mediaselector/5/redir/version/2.0/mediaset/audio-nondrm-download/proto/http/vpid/p02yt3kq.mp3

Content-Disposition: attachment; filename="TheLifeScientific-20150804-GeoffPalmer.mp3"

**Comment by chessgriffin** [comment]
I am no longer maintaining mashpodder but thank you for posting the issue.
