### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by aggsol** [chessgriffin/mashpodder#12]
I am not sure what the license exactly allows in the header of the file as it looks like BSD-2-Clause but the explicit permission to modify and re-distribute are missing. Would you be so kind to clarify those?

Edit: BashPodder claims to be GPL but not which version. Can we assume at least GPLv2?

**Comment by aggsol** [comment]
As the base BashPodder is GPLv3 the same applies here. See https://github.com/lincgeek/bashpodder/issues/2

**Comment by chessgriffin** [comment]
Linc gave me permission years ago to relicense my version as BSD.

**Comment by aggsol** [comment]
@chessgriffin Oh, okay. Is it 2-clause BSD? As I forked mashpodder recently I will make it BSD then.

**Comment by chessgriffin** [comment]
Yes, that's fine, thanks.
