### ISSUE TITLE
Podcasts that require a login

### ISSUE THREAD

**Issue by GrouchyGaijin** [chessgriffin/mashpodder#4]
Is there anyway to use mashpodder to download a podcast that requires a user name and login to access the audio files?

**Comment by mro** [comment]
I don't know if it's ok to mention another (my) podcatcher, but you may have a look at https://github.com/mro/dashpodder - it pulls password protected podcasts and may serve your needs or may not, try it out and tell me.

P.S.: @chessgriffin if you feel objected by my post feel free to tell me so and purge it.

**Comment by chessgriffin** [comment]
I am not maintaining mashpodder any more so no worries.
