### ISSUE TITLE
Keep only x episodes

### ISSUE THREAD

**Issue by flo-assling** [chessgriffin/mashpodder#6]
Hey, this is GREAT work and exactly what I missed on my Raspberry.
Theres only one thing I would need: an option to download _and keep_ only the latest x episodes for a podcast.
An alternative would be an option to sort the M3U in podcast-directories "newest first".

I use a home automation system (Homematic) in combination with PHP scripts on the Raspberry to play M3U Playlists created by your script on my Sonos System, and need the newest episode to play with a key press.

Big thank you, cheers
Florian

**Comment by mro** [comment]
I don't know if it's ok to mention another (my) podcatcher, but you may have a look at https://github.com/mro/dashpodder - it configurably purges old episodes and may serve your needs or may not, try it out and tell me.

P.S.: @chessgriffin if you feel objected by my post, feel free to tell me so and purge it.

**Comment by chessgriffin** [comment]
Hi - I am no longer maintaining mashpodder.  Thanks for posting.
