### ISSUE TITLE
Rename audio files

### ISSUE THREAD

**Issue by efiloN** [chessgriffin/mashpodder#8]
I have a problem with a few podcasts that name their audio files the same.

For example:
> Checking http://rss.acast.com/varvet -- last 5 episodes.
> Found audio.mp3 in feed and in $PODLOG. Skipping.
> Done. Continuing to next feed.

That feed has hundreds of audio files, but it will never download more than one because they're all named audio.mp3. And it will not update if a new audio.mp3 is added to the feed.

**Comment by CentristOuevre** [comment]
This. Anyone got a fix?

**Comment by mro** [comment]
I wrote https://github.com/mro/dashpodder/ for such.

**Comment by chessgriffin** [comment]
I'm no longer maintaining mashpodder.
